name: alexchenlawyer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84415
title: alexchenlawyer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#699eea'
    - '#c0dbf6'
    - '#677b6f'
    - '#534948'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
